add check if doc exist

diff --git a/.github/workflows/swagger-delete.yml b/.github/workflows/swagger-delete.yml
--- a/.github/workflows/swagger-delete.yml
+++ b/.github/workflows/swagger-delete.yml
@@ -25,9 +25,16 @@ jobs:
       - run: npm i --location=global swaggerhub-cli
       - run: |
           VERSION=`echo ${GITHUB_REF_NAME}| sed 's#[^a-zA-Z0-9_\.\-]#_#g'`
-          API_DETAILS=$(SWAGGERHUB_API_KEY=${{secrets.SWAGGERHUB_TOKEN}} swaggerhub api:get "Moira-test-swagger/moira-alert-test/${VERSION}")
-          echo "$API_DETAILS"
-          API_DETAILS=$(SWAGGERHUB_API_KEY=${{secrets.SWAGGERHUB_TOKEN}} swaggerhub api:get "Moira-test-swagger/moira-alert-test/check")
-          echo "$API_DETAILS"
-          SWAGGERHUB_API_KEY=${{secrets.SWAGGERHUB_TOKEN}} swaggerhub api:unpublish "Moira-test-swagger/moira-alert-test/${VERSION}"
-          SWAGGERHUB_API_KEY=${{secrets.SWAGGERHUB_TOKEN}} swaggerhub api:delete    "Moira-test-swagger/moira-alert-test/${VERSION}"
+          SWAGGERHUB_API_KEY=${{secrets.SWAGGERHUB_TOKEN}}
+
+          # Check if the API version exists before attempting to unpublish and delete
+          API_DETAILS=$(swaggerhub api:get "Moira-test-swagger/moira-alert-test/${VERSION}" 2>&1)
+      
+          # If API version details contain "Error: Unknown API", then it doesn't exist
+          if ! echo "$API_DETAILS" | grep -q "Error: Unknown API"; then
+            echo "API version exists, proceeding with removal"
+            swaggerhub api:unpublish "Moira-test-swagger/moira-alert-test/${VERSION}" || true
+            swaggerhub api:delete "Moira-test-swagger/moira-alert-test/${VERSION}" || true
+          else
+            echo "API version not found, skipping removal"
+          fi
